spring:
  application:
    name: workout-catalog-service
  datasource:
    url: jdbc:mysql://localhost:3306/gym_api_workout_catalog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  messages:
    basename: messages
#  cloud:
#    config:
#      enabled: false
#eureka:
#  client:
#    enabled: false
#server:
#  servlet:
#    context-path: /${spring.application.name}